settings:
  all_targeted_commands_bypass:
    enabled: true
    player_list:
      - Player
  void_tp:
    send_message: true
    trigger_y: 0
    worlds:
      - lobby
  announcements:
    enabled: false
    interval: 30 # En segundos